### PR TITLE
TESB-31321:result is not right when run job with thmap and consumer service

### PR DESCRIPTION
**Pull request by csuntalendbj**

### CODE REVIEW

**Review by xldai — APPROVED** [review]
LGTM (backport the fixes from 7.3 to 7.2.1)

**Comment by jgreffe** [comment]
I thought we didn't use patch/x.y.z branches anymore, and stick only to maintenance/x.y branches?

**Comment by xldai** [comment]
You're right! @jgreffe , the PR we can close it.

**Comment by jgreffe** [comment]
@csuntalendbj please close current PR.

**Comment by jgreffe** [comment]
Closing current PR as patch/x.y.z is not used anymore for RT.

**Pull request closed without merging**
