### PR TITLE
TESB-31889 Update of remaining dependencies on vulnerable Jackson versions.

### PR DESCRIPTION
**Pull request by andreasmattes**

### CODE REVIEW

**Review by jgreffe — CHANGES_REQUESTED** [review]
Running `mvn dependency:tree | grep jackson` still displays many other versions

**Comment by andreasmattes** [comment]
Different Jackson versions is not necessarily a problem. We need to get rid only of those with CVEs.

**Comment by andreasmattes** [comment]
I suggest to merge this one and do a scan to see what really remains.

**Review by jgreffe — APPROVED** [review]
lgtm 👌🏼

**Comment by andreasmattes** [comment]
SCA scan of the PR branch does not show further offending Jackson libraries.

**Pull request merged**
