### PR TITLE
TESB-29133 - Update Dom4J to 2.1.3

### PR DESCRIPTION
**Pull request by coheigea**

### CODE REVIEW

**Comment by xldai** [comment]
Better also update the comment lines in the tesb-rt-se/talend-esb/pom.xml, e.g.
```<!-- patch the dom4j version in Camel for TESB-27620 -->```

**Comment by coheigea** [comment]
@xldai Done

**Comment by xldai** [comment]
LGTM

**Comment by xldai** [comment]
Please don't merge it @coheigea , now it's part of the next patch 7.3.1-R2020-06, we can do it together with the PR of TDI, TUP.

**Pull request merged**
