### PR TITLE
TESB-32161 Update STS-related keystores.

### PR DESCRIPTION
**Pull request by andreasmattes**
Replace expired sample keys for STS.

### CODE REVIEW

**Review by jgreffe — COMMENTED** [review]
Seems some are still missing?

./examples/cxf/jaxws-ws-secpol/common/src/main/resources/ws-secpol-wsdl/client.jks
./examples/cxf/jaxws-ws-secpol/common/src/main/resources/ws-secpol-wsdl/cxfca.jks
./examples/cxf/jaxws-ws-secpol/common/src/main/resources/ws-secpol-wsdl/service.jks
./examples/tesb/locator/client/src/main/resources/certs/keystore.jks
./examples/tesb/locator/war/src/main/webapp/certs/keystore.jks
./talend-esb/src/main/distribution/text/container/etc/keystores/keystore.jks

**Review by jgreffe — CHANGES_REQUESTED** [review]
Missing updated Jenkinsfile.build containing new modules for patch

**Comment by jgreffe** [comment]
Please check all changes are ok by building locally: mvn install -DskipTests -Ppatch -pl ...

**Comment by andreasmattes** [comment]
1. The 6 keystores mentioned in the first comment are unrelated to the present fix and do not contain expired keys.
2. Local build with -P patch has succeeded.

**Review by jgreffe — CHANGES_REQUESTED** [review]
Still missing update of Jenkinsfile.build

**Review by jgreffe — APPROVED** [review]
lgtm 👌🏼

**Pull request merged**
