### PR TITLE
Bugfix/master/tesb 31916

### PR DESCRIPTION
**Pull request by xldai**

### CODE REVIEW

**Review by coheigea — CHANGES_REQUESTED** [review]
There are still instances of Jetty coming in from ActiveMQ in the examples

**Comment by xldai** [comment]
upgrade the jetty-all and websocket-server, pl review again @coheigea

**Review by coheigea — CHANGES_REQUESTED** [review]
@xldai There are still some instances of Jetty 9.4.18 coming in from  org.apache.camel:camel-jetty9:jar:2.25.2:compile in examples/camel/jaxrs-jms-http

**Comment by xldai** [comment]
pl review again @coheigea

**Review by coheigea — APPROVED** [review]

**Pull request merged**
