### PR TITLE
TESB-26759 - Update Commons BeanUtils

### PR DESCRIPTION
**Pull request by coheigea**

### CODE REVIEW

**Comment by xldai** [comment]
The commons-beanutils 1.9.3 is still used in our camel-2.23.1-features.xml.
Not sure if we should switch to 1.9.4 or 1.9.3 for now.
Or maybe wait until we do the Camel version upgrade for our 7.3.1?

**Comment by coheigea** [comment]
@xldai Sure we can wait until the Camel upgrade

**Comment by xldai** [comment]
Will cherry pick this commit into the "feature/7.3.1_core_upgrade" branch. Thanks Colm.

**Comment by xldai** [comment]
Done. will close this PR.

**Pull request closed without merging**
