### PR TITLE
TESB-26471 - Update Jettison

### PR DESCRIPTION
**Pull request by coheigea**

### CODE REVIEW

**Comment by xldai** [comment]
We have jettison 1.3.8 defined in the activemq feature xml:
<bundle dependency="true">mvn:org.codehaus.jettison/jettison/1.3.8</bundle>
we may need to patch the activemq feature xml, or it maybe it will be upgraded to 1.4.0 in the newer AMQ feature xml which we possibly will upgrade AMQ for 7.3.1.

**Comment by coheigea** [comment]
@xldai - I submitted a PR to AMQ for 5.15.10: https://github.com/apache/activemq/pull/370

**Comment by xldai** [comment]
@coheigea :thumbsup:

**Comment by jbonofre** [comment]
@coheigea @xldai I'm reviewing/merging the AMQ PR

**Pull request merged**
